version: '3.1'

services:

  webthings-gateway:
    image: mozillaiot/gateway:latest
    restart: always
    volumes:
      - /opt/docker/webthings-gateway:/home/node/.mozilla-iot
    ports:
      - 8080:8080
      - 4443:4443

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin