version: '3.1'

services:

  webthings-cloud:
    build: .
    depends_on:
      - mongo
    ports:
      - 8888:8888
    networks:
      - mongo-network
      - things-network
    environment:
      MONGO_DB_CONNECTION: mongodb://mongo:27017

  webthings-gateway:
    image: mozillaiot/gateway:latest
    restart: always
    networks:
      - things-network
    volumes:
      - E:/Projects/docker/webthings-gateway:/home/node/.mozilla-iot
    ports:
      - 8080:8080
      - 4443:4443

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-network
    # volumes:
    #   - E:/Projects/docker/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin

networks:
  things-network:
    driver: bridge
  mongo-network:
    driver: bridge